### ISSUE TITLE
Android studio

### ISSUE THREAD

**Issue by MRYangY** [lingfengsan/MillionHero#11]
请问怎么运行啊？用as打开项目，找不到运行代码的入口。。

**Comment by lingfengsan** [comment]
设置下SDK，还有就是MAVEN导入pom

**Comment by MRYangY** [comment]
sdk设置过了，maven导入pom ？怎么搞啊？

**Comment by JakeWoki** [comment]
@lingfengsan 
![20180111103936](https://user-images.githubusercontent.com/6948411/34806013-c9beb13e-f6bb-11e7-9af1-f14d06761563.png)
这个是怎么有的？

**Comment by apkcore** [comment]
这是intelliJ idea

**Comment by ananas-xxj** [comment]
@MRYangY as运行了吗  as导入resource目录没了啊
