### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: net/sourceforge/tess4j/TesseractException

### ISSUE THREAD

**Issue by muwu324** [lingfengsan/MillionHero#13]
大佬好，报错Exception in thread "main" java.lang.NoClassDefFoundError: net/sourceforge/tess4j/TesseractException。然后tess的jar包和路径是没有问题的，请问可能是什么问题呢？
谢谢！

**Comment by lingfengsan** [comment]
是使用MAVEN导入的吗？让maven自动加载包就可以的
