### ISSUE TITLE
Failed loading language 'chi_sim' Tesseract couldn't load any languages!

### ISSUE THREAD

**Issue by kaina404** [lingfengsan/MillionHero#14]
MAC上面执行，一直卡在这个报错中。
`Failed loading language 'chi_sim'
Tesseract couldn't load any languages!`
开发环境是
IntelliJ IDEA 2017.3.2 (Community Edition)
Build #IC-173.4127.27, built on December 26, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3

tesseract/3.05.01

求解决啊

**Comment by lingfengsan** [comment]
使用MAVEN导入的吗。感觉像是项目找到Tessdata文件夹

**Comment by kaina404** [comment]
我这边手动指定了位置了，还是报这个错误，但是在命令行中运行是没问题的。

**Comment by lingfengsan** [comment]
建议使用maven构建下项目。就把pom添加进去。就不用管环境问题了

**Comment by AotoriChiaki** [comment]
Failed loading language 'chi_sim'我解决了

解决方案是要手动把tessdata文件夹扔到C:\Users\用户名\AppData\Local\Temp\tess4j

**Comment by JuanbingTeam** [comment]
debug了下，mac上应该是Tess sdk里的问题。  dataDirectory没问题, 能加载到的。

**Comment by amosannn** [comment]
同样的问题，是tess4j的陈年旧bug了 [https://github.com/nguyenq/tess4j/issues/26]()

**Comment by liulance** [comment]
这个错误有人解决了吗？我这边也是这个错误
