### ISSUE TITLE
正确答案判定存在问题

### ISSUE THREAD

**Issue by ZbkSou** [lingfengsan/MillionHero#21]
```
  ans[i] = (float)countQA[i] / (float)(countQuestion * countAnswer[i]);
```
这个这样计算匹配值会有问题,不如直接比较countQA.

**Comment by lingfengsan** [comment]
理论上是这个公式比较准。可以看下以下这篇文章。另外结合打开的网页搜索比较好
https://en.wikipedia.org/wiki/Pointwise_mutual_information

**Comment by ZbkSou** [comment]
学习到了

**Comment by AotoriChiaki** [comment]
实际测试发现正确率真的很低。
能不能实现直接在打开的页面做答案的关键词匹配，返回匹配次数，推荐答案为匹配次数最高的那个，或者直接输出匹配程度排序，方便用户作答否定类题目

**Comment by ZbkSou** [comment]
@AotoriChiaki 用问题的搜索结果页面的文字统计关键词词频,应该就准了

**Comment by BinarySatan** [comment]
实在是太不准了。。。。
