### ISSUE TITLE
截屏问题

### ISSUE THREAD

**Issue by kakarottoll** [lingfengsan/MillionHero#22]
Process process = Runtime.getRuntime().exec(ADB_PATH
                        + " shell /system/bin/screencap -p /sdcard/screenshot.png");
while (process.isAlive()) {
          Runtime.getRuntime().exec(ADB_PATH
                        + " pull /sdcard/screenshot.png " + curPhoto.getAbsolutePath());
}
改成这样可以保证保存在电脑的图片数据不为空
sleep 700ms 有可能造成截屏没完成就进行pull

**Comment by hubuwx** [comment]
cannot resolve symbol 'exec'???

**Comment by kakarottoll** [comment]
写错了，尴尬-- process 我测试代码里写的exec

**Comment by AotoriChiaki** [comment]
Error:(36, 31) java: 找不到符号
  符号:   方法 isAlive()
  位置: 类型为java.lang.Process的变量 process

这个怎么解决……

**Comment by kakarottoll** [comment]
你再试试，我process.isAlive()的process之前发的时候不小心多了个 （空格），重新复制试试

**Comment by AotoriChiaki** [comment]
嗯，还是不行，因为之前我就删掉空格试过了……

**Comment by kakarottoll** [comment]
用作者的最新代码也可以，你试一下

**Comment by fgcui1204** [comment]
有没有出现截图很慢的情况，截图+把图片复制到电脑上两个过程大概5s

**Comment by zoukun120** [comment]
作者用的是  process.waitFor();

**Comment by zoukun120** [comment]
但是还是会提示‘找不到图片’，你门有什么好办法吗
