### ISSUE TITLE
如果手机没有sd卡的话,截取上传到电脑的图片是空的?

### ISSUE THREAD

**Issue by Ggsdl** [lingfengsan/MillionHero#28]
如果是这样的话, 应该怎么样修改对应 代码中sd卡的路径呢?
尝试这样去写:
/storage/emulated/0/screenshot.png
结果不可行

**Comment by AotoriChiaki** [comment]
没有sd卡也是可以运行的啊，我的就是

**Comment by mangoIngithub** [comment]
有可能是手机系统截屏慢，我也改了地址，一开始跑了还是空，但调试的时候可以通过，我就加长了线程休眠时间。这样就有图片了   你首先看看你修改的位置 本机里有没有你截的屏

**Comment by Ggsdl** [comment]
确实是截屏时间长,改2秒就有了
