### ISSUE TITLE
你好，问题如下

### ISSUE THREAD

**Issue by liulance** [lingfengsan/MillionHero#33]
![image](https://user-images.githubusercontent.com/22095781/34871880-1832efa6-f7ca-11e7-9015-3877c1d37187.png)
你好，用intellij 导入项目，运行报错，请问如何解决，谢谢

**Comment by zhaopeng1234** [comment]
你用maven clean过了吗？

**Comment by lingfengsan** [comment]
这都是maven自动导入的，使用maven clean可以解决
