### ISSUE TITLE
对高分辨率的支持还是不太友好。。

### ISSUE THREAD

**Issue by zhaopeng1234** [lingfengsan/MillionHero#35]
希望能够在单题运行完之后保存的图片上标识出识别区域，便于调节函数参数。。另外要是能够在信息输出的时候增加时间戳就好了，便于改进程序

**Comment by lingfengsan** [comment]
现在更新新版程序了，可以在响应的地方适配自己的手机

**Comment by zhaopeng1234** [comment]
你好，我对这个项目很有兴趣，想参与这个项目的维护和更新，请问有qq交流群吗？ zhaopeng1234 邮箱：zhaopeng1234@gmail.com 签名由 网易邮箱大师 定制 在2018年01月12日 21:43，lingfengsan 写道： Closed #35. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
