### ISSUE TITLE
结果为啥完全看不懂

### ISSUE THREAD

**Issue by liu-xinhui** [lingfengsan/MillionHero#51]
![image](https://user-images.githubusercontent.com/7698511/34924548-0372f40a-f9df-11e7-9889-6af663806169.png)
并且会打开浏览器,搜索的内容也很奇怪

**Comment by liu-xinhui** [comment]
![image](https://user-images.githubusercontent.com/7698511/34924586-3a7600f0-f9df-11e7-8edb-5efad44c412b.png)

**Comment by fgcui1204** [comment]
修改一下截取字符串的代码就好了，前边log_id: xxxxxxxxxxxx, words_result这一部分的长度是固定的

**Comment by lingfengsan** [comment]
更新一下代码。百度OCR已经完成。需要搭建下环境，见wiki里面的使用说明
