### ISSUE TITLE
提取文字失败：javax.imageio.IIOException: I/O error reading PNG header!

### ISSUE THREAD

**Issue by ftx0day** [lingfengsan/MillionHero#8]
不知道是不是读存问题，大概总是到5.6次成功这样子，分辨率也是1080的，求解

**Comment by lingfengsan** [comment]
现在更新成输入回车才会读取图片了。
一直读图片感觉不如回车。。。

**Comment by wkp111** [comment]
图片不完整，你看一下图片是否可以打开？因为cmd命令需要时间，再加上图片大小不一，缓存时间和复制移动时间均不固定，会导致图片不完整。
